# Also try deploying to Aliyun FC later
name: Package the application and upload it to AWS EC2.

# Install git, npm, pm2 firstly on the EC2 instance.

on:
    workflow_dispatch: # trigger the workflow manually
    push:
        branches:
            - deploy

jobs:
  Deploy:
      name: Deploy to EC2
      runs-on: ubuntu-latest

      steps:
        - name: Build & Deploy
          env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
            REMOTE_HOST: ${{secrets.REMOTE_HOST}}
            REMOTE_USER: ${{secrets.REMOTE_USER}}
            OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
            AUTH_TOKEN: ${{secrets.AUTH_TOKEN}}

          run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              # Now we have got the access of EC2 and we will start the deploy .
              cd ~/workspace/chatgpt-api-proxy/ ;
              echo "$OPENAI_API_KEY" > .env ;
              echo "$AUTH_TOKEN" > .env" ;

              echo '------ cd done ------' ;
              git checkout deploy ;
              git checkout . ;
              git pull origin deploy ;
              echo '------ git pull done ------' ;
              npm install ;
              npm run prod ;
              echo '------ chatgpt-api-proxy is running ------' ;
              '
            rm -rf private_key
